name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Update repository metadata
      run: sudo apt-get update
    - name: Install python
      run: sudo apt-get install python3 python3-pip python3-setuptools python3-wheel
    - name: Install meson
      run: pip3 install --user meson
    - name: Install build essential
      run: sudo apt-get install build-essential valac gettext cmake git appstream-util desktop-file-utils
    - name: Install library headers
      run: sudo apt-get install libgee-0.8-dev libjson-glib-dev libsoup2.4-dev libglib2.0-dev libgtk-3-dev
    - name: Configure project
      run: meson build
    - name: Build project
      run: ninja -C build
